# Generated by Django 3.1.1 on 2020-09-19 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distrik',
            fields=[
                ('id_distrik', models.IntegerField(primary_key=True, serialize=False)),
                ('distrik', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['id_distrik'],
            },
        ),
        migrations.CreateModel(
            name='Kampung',
            fields=[
                ('id_kampung', models.IntegerField(primary_key=True, serialize=False)),
                ('kampung', models.CharField(max_length=30)),
                ('distrik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kampungs', to='penjualan.distrik')),
            ],
            options={
                'ordering': ['id_kampung'],
                'unique_together': {('distrik', 'id_kampung')},
            },
        ),
        migrations.CreateModel(
            name='Nelayan',
            fields=[
                ('id_nelayan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_nelayan', models.CharField(max_length=150)),
                ('status_nelayan', models.CharField(max_length=20)),
                ('perahu', models.CharField(max_length=20)),
                ('tgl_lahir', models.DateField()),
                ('distrik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penjualan.distrik')),
                ('kampung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penjualan.kampung')),
            ],
        ),
    ]
